### ISSUE TITLE
The game lags a lot

### ISSUE THREAD

**Issue by cubelot** [maitian352/still-mesa-50010#6]

**Comment by cubelot** [comment]
Oh Today I Was Playing On Bajie:2000 And When I Went To FFA Mode In Ranger, I Started Flashing And Disappeared!
And I Cant Move!

**Comment by SampleProvider** [comment]
It has been happening for me too!

**Comment by cubelot** [comment]
When I use Arrow Rain, the game lags a lot.

**Comment by cubelot** [comment]
.

**Comment by Tianmu695** [comment]
.
.
.
.

.
.
.
..

..
.
.
.
.
.

.
.
.
.
.
.
.
..
.
.
.
.
.
.
..
.
.
.
.
.
.
.

.
.
.

**Comment by cubelot** [comment]
.

**Comment by SampleProvider** [comment]
Fixed. The arrow don't delete themselves for a very long time and it can cause the server to lag.
